### ISSUE TITLE
Como desintalar el StardustCFW

### ISSUE THREAD

**Issue by DSMan97** [StarDustCFW/StarDustCFWPack#10]
Tras la instalación de vuestro CFW me gustaría saber como desintalarlo para recuperar el logo de Switch en el arranque y quitar el fondo que tiene el hekate.

Gracias

**Comment by Kronos2308** [comment]
`Oh sheet here we go again`

Creo que ya te respondí a eso 

Borra todo menos la carpeta nintendo
