### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by Staichi54** [StarDustCFW/StarDustCFWPack#11]
Esto es basicamente una pregunta, mas que un error ni nada ya que me anda bien el satrdust, pero, como quito o muteo la musica del fondo? la que suena en el incio ya que tambien suena en todos los juegos y eso me empieza a molestar, e intentado entrar a todas las app que tiene y ninguna me deja quitar la musica, como lo puedo hacer?

**Comment by Kronos2308** [comment]
L R B 
O desactiva el servicio sysplay

**Comment by Staichi54** [comment]
Gracias
