### ISSUE TITLE
stardust no boot con sx xecuter modchip (flashed o no flashed) en un (MARIKO) unit

### ISSUE THREAD

**Issue by PASTO666** [StarDustCFW/StarDustCFWPack#12]
como dice el titulo, no funciona en V2 marico unit pero si funciona con modchip (flashed) na mas en un V1 erista :( Aun no tienen la forma de boot con stardust en mariko? Yo se que con RR retro reloaded si funciona pero con ese se nesecita el sx os license el cual hoy dia no se puede adquirir ya que la pagina esta down ya hacen days.. y sin dicha license no nos funciona tinfoil con RR :( En stardust no se nesecita dicha license para usar tinfoil.

**Comment by Kronos2308** [comment]
el soporte para version 2 se esta trabajando para q funcione de forma nativa 
prueba el ultimo master

**Comment by Kronos2308** [comment]
como parche temporal solo edita el boot.ini
en file pon 
/StarDust/payloads/Atmosphere.bin

**Comment by PASTO666** [comment]
ok gracias, tratare eso que dices. :)
