### ISSUE TITLE
paquetes corruptos

### ISSUE THREAD

**Issue by Sigfryd** [StarDustCFW/StarDustCFWPack#13]
Buen dia  Kronos2308 , cuando bajo el CFW 2.26 del repositorio , tanto el tar como el zip estan corruptos, podrias revisar essto por favor?? muchas gracias

**Comment by Kronos2308** [comment]
pues ya me diras q estas haciendo mal tu 
![imagen](https://user-images.githubusercontent.com/36446521/118133043-3eb14b80-b3f8-11eb-8ea7-c41d0aef456f.png)

**Comment by Sigfryd** [comment]
Buen dia Kronos , si a lo que veo se descargo en mi hogar mal , lo
descargue en mi trabajo y todo en orden , solo una pregunta?? tu CW soporta
12.0.2? muchas gracias por la atencion saludos cordiales

[image: image.png]

**Comment by Kronos2308** [comment]
Si pero debes aplicar el parche beta

**Comment by Sigfryd** [comment]
Como se empieza a buscar este parche o como lo busco??? Y le doy una
checada, gracias

**Comment by Sigfryd** [comment]
Buen dia Kronos, ya realice el backup de la micro y realice la
particion para la emunand en hekate , pero al momento de correr el
atmosphere sale el siguiente error cabe senalar que estoy utilizando los
siguientes FW puesto que el switch tiene la version 12.0.2

atmosphere-0.19.3-master-691a453d+hbl-2.4.1+hbmenu-3.4.0
fusee_ fs patches for HOS 12.0.2
hekate_ctcaer_5.5.6_Nyx_1.0.3

sin mas muchas gracias  bro saludos

[image: WhatsApp Image 2021-05-19 at 6.44.53 AM.jpeg][image: 2.jpeg][image:
3.jpeg][image: 4.jpeg][image: 5.jpeg]

**Comment by Kronos2308** [comment]
Saca el cartucho

**Comment by Sigfryd** [comment]
Buen dia kronos2302, para la nueva version de CFW stardust 12.0.3 se
realiza lo siguiente para descartar errores en los pasos que comentas, se
realiza el formateo en el apartado del video que tienes para la emunand
paso a paso definitivo al igual que se activa la emunand , al tener esto se
activa la opcion de atmosphere que la emunand ha sido creada con exito ,
pero al momento de querer entrar a la emunand marca el siguiente error

a fatal error occurred when running atmosphere program id 0100000000000004

para esto se revisa los siguientes puntos:
Que no tenga el cartucho como comentas
Que la micro sd este bien particionada
Que no tenga conexion a internet
Se activor el modo incognito


despues de esto te pide que presiones el boton de POWER al realizar esto
ahora marca la siguiente falla que te anexo , repito esto para el CFW
12.0.3, sin mas muchas gracias !!
