### ISSUE TITLE
RipJKAnime_NX, se cierra solo el reproductor de video.

### ISSUE THREAD

**Issue by Thyrnt** [StarDustCFW/StarDustCFWPack#14]
Buenas tengo un problema con la aplicacion RipJKAnime_NX, desde que actualicé el sistema de Nintendo a la versión 12.1.0, atmosphere a 0.19.5 y hekate ctcaer a 5.5.8, la aplicación abre normalmente, se puede seleccionar distintos animes y reproducirlos pero luego de aproximadamente 6 minutos se cierra automáticamente mostrando un diálogo "Se va a cerrar esta pantalla" y te regresa al menú donde escoges los animes, intenté solucionarlo borrando la aplicación pero el resultado fue el mismo.

![2021072513553000-EFFB08ECEF4EBC5640D908A23A7CAC96](https://user-images.githubusercontent.com/86402841/126947934-c2e1d513-b45f-40fb-9159-37199e605fb9.jpg)

Otro usuario también tiene el mismo problema:
https://github.com/darkxex/RipJKNX/issues/52#issue-946656171

Si alguien supiera una solución.

**Comment by Kronos2308** [comment]
Que servidor estás usando 
Tienes algun dns puesto ?
COn que animes pasa
Estás usando el último build? Nsp

**Comment by Kronos2308** [comment]
Intenta cambiar el tiempo de esperade la switch uiza es por el dimming

**Comment by Thyrnt** [comment]
Hola, gracias por la ayuda, soy un poco paranoico con el tema de evitar ban, por eso uso en la consola blank prodinfo, dns.mitm, 90dns pero nunca ocurrió estos problemas y hace unos dias agrege lock-logs, acabo de probar quitándo lock-logs mediante su aplicación y aumentar el tiempo de espera en la consola pero es resultado es el mismo.

**Comment by Thyrnt** [comment]
Perdon por error precione cerrar el problema.

Se cierra el reproductor sólo, con cualquier anime y servidor, uso el nro y lo ejecuto presionando "R" antes de inciar un juego, soy un poco paranoico con el tema de evitar ban, por eso uso en la consola blank prodinfo, dns.mitm, 90dns pero nunca ocurrió estos problemas y hace unos dias agrege lock-logs, acabo de probar quitándo lock-logs mediante su aplicación y aumentar el tiempo de espera en la consola pero es resultado es el mismo.

Gracias por la ayuda

**Comment by Kronos2308** [comment]
hay es donde esta el problema 
tines que instalar el nsp no el nro el nro ya se dejo de usar

**Comment by Thyrnt** [comment]
Descargo el nsp del autor original o tu tienes uno personalizado?

**Comment by Thyrnt** [comment]
Instale el nsp y volvio a ocurrir lo mismo, no se cual podrá ser el problema, ademas antes de actualizar atmosphere y hekate ctcaer borré todos los archivos antiguos para que sea una actualización limpia.

**Comment by Kronos2308** [comment]
https://github.com/StarDustCFW/RipJKNX/tree/master/out

**Comment by Thyrnt** [comment]
Hola, acabó de probar los nsp de tu link y sigue el mismo problema, agradesco toda la ayuda que das.

**Comment by Kronos2308** [comment]
pues la verdad no se 
aumenta el tiempo de espera de la switch a ver

**Comment by Kronos2308** [comment]
en mi caso no pude reproducir el error 
si puedes mandarme un video del error seria de ayuda

**Comment by Thyrnt** [comment]
Aca esta el video:


Encontré algo interesante, al bajar el firmware a 11.0.1 que es el que tenia antes de actualizar a 12.1.0 se solucionó el problema, creo hay algo con la actualizacion que provoca esos errores, lo que no se si la actualización que yo descargue de la aplicación all-in-one switch updater estara corrupto o mal subido?, me podrías decir de donde descargas tus firmwares para yo instalarlo y hacer la prueba.

**Comment by Kronos2308** [comment]
usa el StarDust toolkit

**Comment by Kronos2308** [comment]
![r](https://lewd.pics/p/UQXq.jpg)

**Comment by darkxex** [comment]
La verdad ya lo estimaba que fuera un problema del firmware 12, debieron afectar a las funciones internas del navegador.

**Comment by Kronos2308** [comment]
estoy en 12.1.0

**Comment by Kronos2308** [comment]
es que a mi no se me cierra .
porque,,, yolo

**Comment by darkxex** [comment]
Lo otro es lo q dices, deben estar usando dns personalizadas.

**Comment by Kronos2308** [comment]
es que porque se cierra ?
entiendo que con mix drop y  nozomi pase pero los otros servers no usan en reproductor directamante o sea que crashea el web entero
Raro

**Comment by Kronos2308** [comment]
haciendome la paja emntal podria estimar que nintedo añdio un parametro para controlar la duracion de los videos ?

**Comment by darkxex** [comment]
La verdad no me ha pasado eso, así que también desconozco la razón, a la tarde revisaré q tal funciona.

**Comment by Kronos2308** [comment]
mmmmm
@Thyrnt estas usando algun dns , incognito o algo que se eta con la red como lo de los auriculares bluetooth o algo asi ?

**Comment by Kronos2308** [comment]
@darkxex  bueno lo ultimo que toke fue arreglar lo de mixdrop que hay algunos videos que no se estan subiendo a nozomi 
pero no creo que tenga que ver con eso

**Comment by Kronos2308** [comment]
printf("SetCapConfigs\n");
			webConfigSetDisplayUrlKind (&config, false);
			webConfigSetMediaPlayerAutoClose (&config, true);
			//play direct links
			//if(url.substr(9,9) == "-delivery" || url.find("apidata.googleusercontent")) 
			webConfigSetBootAsMediaPlayer(&config, true);
			//webConfigSetFooter(&config, false);


webConfigSetMediaPlayerAutoClose (&config, true);
lo unico que hace es cerrar el reproductor cuando el video finaliza

**Comment by Thyrnt** [comment]
soy un poco paranoico con el tema de evitar ban, por eso uso en la consola blank prodinfo, dns.mitm (configurado como 90dns), en configuración de internet 90dns pero nunca ocurrió estos problemas y hace unos dias agrege lock-logs.

**Comment by Kronos2308** [comment]
poner incógnito es mas  q suficiente

**Comment by Kronos2308** [comment]
no sea exagerado

**Comment by Thyrnt** [comment]
No tengo dinero para comprar otra consola, de ahí mi temor a ser baneado, tú sólo usas incognito?

**Comment by Thyrnt** [comment]
Ya lo actualicé voy a ver que tal va

**Comment by Kronos2308** [comment]
claro

**Comment by Kronos2308** [comment]
si te banean por usando incógnito
ya te puede caer u n rayo en un dia de sol

**Comment by Thyrnt** [comment]
Jaja, me haces reir.

**Comment by Thyrnt** [comment]
Ya lo probe y se volvio a cerrar 😢, voy a intentar quitando los dns o algo que se me ocurra, haber si encuentro alguna solucion, como último recurso voy a formatear mi tarjeta sd y empezar desde cero.

**Comment by Thyrnt** [comment]
Por curiosidad no tendrás alguna versión más antigua? para ver si hay algún cambio.

**Comment by darkxex** [comment]
Quita las dns, con incógnito no te banean y prueba.

**Comment by Kronos2308** [comment]
Por favor no formatees la micro SD eso es bastante inútil
Están todas en el historial de Github busca por commits

Por cierto quita los DNS y pon los de Google 
8.8.8.8 - 8.8.4.4
O déjalo en automático quita el  default.txt de los host de atmosphere y deja el por defecto 
El lock logs yo también lo tengo así que no afecta a eso 
Ya si nos ponemos más técnicos podríamos ir y borrar el save data del navegador

**Comment by Thyrnt** [comment]
Ok, voy a intentar todo lo que me dicen.

**Comment by Kronos2308** [comment]
No me acuerdo 
Son una pila así q de memoria no me se el save ID

**Comment by Thyrnt** [comment]
Ya probé quitando el dns, poniendo en automático, poniendo el de Google y no funcionó pero al dejar solo el host por defecto de atmosphere sin ningún tipo de dns se solucionó el problema, son unos capos en serio, encontraron el problema y ya puedo ver sin que se corte el vídeo.

Aún así me da curiosidad como en la version 11.0.1 del sistema no ocurren esos problemas con todos los dns que tenia, pero en la version 12.1.0 si hay problemas.

Gracias de verdad por toda su ayuda

**Comment by darkxex** [comment]
@Kronos2308 recuerdas la librería mizuki hacked que hice? pienso hacer una librería igual para Fembed, de modo que tenga lanzamiento directo y para descarga. te aviso para que revises mañana la implementación y veas que tal anda.

**Comment by Thyrnt** [comment]
Ignoro el tema pero solo como sugerencia es posible poner algo que habilite algún tipo de logs, algo parecido a lo que tiene dns.mitm o cuando ocurre un error en atmosphere o windows (pantalla azul) que sirve para ver los registros de la aplicación y saber cual fue el problema.

Y de nuevo gracias por la ayuda.

**Comment by Kronos2308** [comment]
Los logs se guardan en atmosphere

**Comment by Kronos2308** [comment]
@darkxex  ok tu me avisas

**Comment by Kronos2308** [comment]
Ya que el problema era el hist de atmosphere cierro está issue

**Comment by 4ngeloco** [comment]
> Ya probé quitando el dns, poniendo en automático, poniendo el de Google y no funcionó pero al dejar solo el host por defecto de atmosphere sin ningún tipo de dns se solucionó el problema, son unos capos en serio, encontraron el problema y ya puedo ver sin que se corte el vídeo.
> 
> Aún así me da curiosidad como en la version 11.0.1 del sistema no ocurren esos problemas con todos los dns que tenia, pero en la version 12.1.0 si hay problemas.
> 
> Gracias de verdad por toda su ayuda

hola Thyrnt, disculpa soy algo novato en este tema, me podrias orientar de como le hago para eliminar los dns y dejar el host por defecto, lo hago desde algun ajuste o configuracion desde la consola o desde algun archivo? necesito ayuda por favor tya que estoy teniendo el mismom problema del cierre de los videos, y no encuentro ninguna solucion, hise un downgrade pero no funcionó. muchas gracias de antemano.

**Comment by 4ngeloco** [comment]
> Ya que el problema era el host de atmosphere cierro está issue

buenas noches kronos, pordia ayudarme porfavor, soy novato y estoy teniendo este problema del cierre, como le hago para eliminar los dns y dejar el host por defecto como comentaba Thynrt? muchas gracias de antemano bro. No encuentro solucion al problema

**Comment by Kronos2308** [comment]
Borrar de Atmosphere/hosts todo excepto default.txt

**Comment by 4ngeloco** [comment]
> Borrar de Atmosphere/hosts todo excepto default.txt

gracias kronos por tu pronta respuesta, me sale esto 
# Nintendo telemetry servers
127.0.0.1 receive-%.dg.srv.nintendo.net receive-%.er.srv.nintendo.net 

y en el exosphere.ini tengo esto
[exosphere]
debugmode=1
debugmode_user=0
disable_user_exception_handlers=0
enable_user_pmu_access=0
blank_prodinfo_sysmmc=1
blank_prodinfo_emummc=1
allow_writing_to_cal_sysmmc=0
log_port=0
log_baud_rate=115200
log_inverted=0

habra mucho riesgo de ban para solo ver anime dejando solo el default? esta instalado el apk de ripjkanime. muchas gracias

**Comment by Kronos2308** [comment]
No uses ningún dns

**Comment by 4ngeloco** [comment]
> No uses ningún dns

hay mucho riesgo de ban sin dns?

y esto debo dejarlo en default o lo borro:

* Nintendo telemetry servers
127.0.0.1 receive-%.dg.srv.nintendo.net receive-%.er.srv.nintendo.net

**Comment by darkxex** [comment]
Solo borra la app y ya. Ve anime por un celular o compra crunchyroll.

**Comment by Kronos2308** [comment]
@4ngeloco pues igual deberías leer porque está todo explicado ya si te da pereza leertelo ya nones cosa mía las instrucciones son claras si lo las sigues y falla pues ya no es problema de la app

**Comment by 4ngeloco** [comment]
> @4ngeloco pues igual deberías leer porque está todo explicado ya si te da pereza leertelo ya nones cosa mía las instrucciones son claras si lo las sigues y falla pues ya no es problema de la app

me esta rompiendo el coco, he hecho todo, dejar solo defecto, llegue a unpost tuyo que venia reparado, lo instale el nsp, el tema es que se actualiza automaticamente solod e todas formas, no se como detenerlo para que no me lo actualice, el problema persiste del cierre, editando las dns de la conexion y desde los archivos, con y sin dns, no hay forma de que no se me cierre pasado los 5 a 6 minutos, y no me deja evitar la actualizacion de la app para haber usado la que subiste supustamente con la solucion incorporada. quizas sea por estar en la 16.0.3? ud la puede usar sin problemas en esta version? tengo incognito activado igual...

**Comment by Kronos2308** [comment]
Usa siempre la última deja la app actualizarse no la instales en la nand sino en la SD
Quita los DNS y hosts y reinicia la consola para que se apliquen los cambios

**Comment by 4ngeloco** [comment]
> Usa siempre la última deja la app actualizarse no la instales en la nand sino en la SD Quita los DNS y hosts y reinicia la consola para que se apliquen los cambios

buscare otro metodo para ver anime. vi que eres uno de los creadores, quiero comentarte que la app esta con problemas, ya que el error persiste de manera constante...
desintale la .nro que tenia, y descargue tu nsp de este link: https://github.com/darkxex/RipJKAnimeNX/releases/2.4.3
antes y despues d ela instalacion, elimine todos los datos, tambien los host dejando solo el de defecto. entra la app una vez instalada, y se actualiza sola actualizando tambien la configuracion de los host, la primera vez que lo his tube suerte ya que pude realizar busquedas y reproducir varios capitulos, vi unas 2 horas aproximado, hasta que llego el fastidioso error del cierre automatico, tras varios intentos reinstalando, borrando saves y host, reiniciando, el problema persiste de manera constante, tras abrir el primer capitulo luego de una reinstalacion, este se puede cerrar durante el primer minuto... eso mas que nada darte las gracias por el apoyo de todas formas, segundo informarte como eres el creador, y mas nada, una pena, estaba bien pro la app pero la estan pinchando.

**Comment by darkxex** [comment]
> > Usa siempre la última deja la app actualizarse no la instales en la nand sino en la SD Quita los DNS y hosts y reinicia la consola para que se apliquen los cambios
> 
> buscare otro metodo para ver anime. vi que eres uno de los creadores, quiero comentarte que la app esta con problemas, ya que el error persiste de manera constante... desintale la .nro que tenia, y descargue tu nsp de este link: https://github.com/darkxex/RipJKAnimeNX/releases/2.4.3 antes y despues d ela instalacion, elimine todos los datos, tambien los host dejando solo el de defecto. entra la app una vez instalada, y se actualiza sola actualizando tambien la configuracion de los host, la primera vez que lo his tube suerte ya que pude realizar busquedas y reproducir varios capitulos, vi unas 2 horas aproximado, hasta que llego el fastidioso error del cierre automatico, tras varios intentos reinstalando, borrando saves y host, reiniciando, el problema persiste de manera constante, tras abrir el primer capitulo luego de una reinstalacion, este se puede cerrar durante el primer minuto... eso mas que nada darte las gracias por el apoyo de todas formas, segundo informarte como eres el creador, y mas nada, una pena, estaba bien pro la app pero la estan pinchando.

Si tienes Android descarga esto. https://github.com/darkxex/Rip/releases/download/148/ripjka148.apk es la misma cosa pero en Android.

**Comment by Kronos2308** [comment]
A ver Capo la última de aquí https://github.com/darkxex/RipJKAnimeNX/releases caramba 
A ver papá no se porque te pasa eso porque la app funciona perfectamente no tiene ningún bug y como eres el único que le pasa voy a dar por cerrado este asunto
Mi solución definitiva es `no  veas anime`
