### ISSUE TITLE
Momento XDDDD.

### ISSUE THREAD

**Issue by darkxex** [StarDustCFW/StarDustCFWPack#16]
me creerías que me insultaron porque la app es para gente que habla español? https://github.com/darkxex/RipJKNX/issues/79

**Comment by Kronos2308** [comment]
@darkxex  Biembenido al lado oscuro 
hay quien si no hablas ingles te miran como un leproso 
solo para darles en la cabeza, quieres que haga todos los pull en español?

**Comment by Kronos2308** [comment]
![jajaja](https://cdn.discordapp.com/emojis/552074378238492692.png?v=1&size=64 )

**Comment by Kronos2308** [comment]
@darkxex  te recomiendo discord https://discord.gg/kscctYj
