### ISSUE TITLE
Sxos

### ISSUE THREAD

**Issue by mcbeth1935** [StarDustCFW/StarDustCFWPack#22]
Hola acabo descubrir este pack stardustcfw pero quisiera saber si esta funcionando sxos porque en el pack que tengo,  tengo una emmunand de ams y otra de sxos y esta ultima ha dejado de funcionar por las constantes actualizaciones  del ofw

**Comment by Kronos2308** [comment]
No sxos está completamente descontinuado y solo funciona con una emunand en 11.0.0 o inferior

**Comment by mcbeth1935** [comment]
Claro tienes razón pero a lo que me refiero es que yo tengo dual boot de emmunand con  emmunand de ams a la ultima versión y funciona perfecto y sxos en emmunand con fw 11 y mi switch en stock siempre estaba a la ultima version pero por las actualizaciones del ofw de nintendo me ha dejado de funcionar el booteo de la emmunand de sxos y ese problema ha empezado desde la actualizacion 16.0.0 entonces al ver tu pack de stardust veo de que hay la opción de doble booteo de las emmunand de ams y sxos y quería saber si en tu pack sigue funcionando la opción de bootear la emmunand de sxos

**Comment by Kronos2308** [comment]
Si es la opción de link sxos emu to ams
