### ISSUE TITLE
Install with Picofly rp2040

### ISSUE THREAD

**Issue by ShaviTF** [StarDustCFW/StarDustCFWPack#23]
Trying to install it on a Mariko with picofly rp2040, when the system boots, it does not open the StarDust menu, failing that, it tries to open Atmosphier directly and it hangs on a black screen

  Any suggestions?

**Comment by Kronos2308** [comment]
Use a SD on fat32

**Comment by ShaviTF** [comment]
I do extFAT... if i install other packs like for example https://nintricks.github.io/magia-nintricks/ works without issues...

**Comment by Kronos2308** [comment]
Use fat32 SD format to avoid compatibility issues

**Comment by ShaviTF** [comment]
Ok... Finally, the behavior did change when formatting to FAT32 (instead of extFAT), but the problem has now gotten worse... that is, now when turning on it does not enter the StarDust menu or enter Hekate, failing that, it directly entered atmosphier with what has gotten me dirty with SYSNAND... any suggestions? 😅

**Comment by Kronos2308** [comment]
Has long has you not install any game the nand is still clean 
Press vol - to enter on Hekate on the boot

**Comment by ShaviTF** [comment]
Ok... i could restore from a BackUp i do before change file system to Fat32 ... at this poit Atmosphere did not boot complete... so i hope its a clean image of the Sysnand... In other hand... Have you tested StarDustCFW in Mariko systems?... i cant find the way to boot the StarDust menu... if go into hekate and try to open stardust payload i get black screen

**Comment by Kronos2308** [comment]
Stardust menú only work on older switch hardware
So for Mariko Hekate is used instead

**Comment by Kronos2308** [comment]
For boot issues like the one that happen for using haku33 you must apply a fix  but that's another history
