### ISSUE TITLE
Stardust needs the official atmosphere 0.11.1 :) plz update..

### ISSUE THREAD

**Issue by PASTO666** [StarDustCFW/StarDustCFWPack#5]
Stardust needs the official atmosphere 0.11.1 :)  plz update.. Also incognito has new update for firmware 10.0.0 compatible :)

**Comment by Kronos2308** [comment]
https://cdn.discordapp.com/attachments/619916581635620904/700086536917614612/pkg1.bin

put this inside StarDust/
to get incognito working again

**Comment by Kronos2308** [comment]
is a small patch but work

**Comment by PASTO666** [comment]
Ok thx.. since i see in this pack the atmos pre-launch 1.... The official atmosphere 0.11.1 is out now :) just for the heads up.. thx again for your releases... you should wait for every app to get updated and then u release a 100% compatible pack for 10.0.0 :) for example all updated payloads for, incognito, lockpick, sx os ect ect.. and yea one of the important one the theme changer NxThemeInstaller.nro for 10.0.0.... Gracias una ves mas kronos... me encanta su StardustCfw cada ves mas :)

**Comment by Kronos2308** [comment]
i will make anew release 
use this to then https://github.com/StarDustCFW/StarDustCFWPack/archive/master.zip
