### ISSUE TITLE
Tinfoil doesnt work with normal atmosphere

### ISSUE THREAD

**Issue by PASTO666** [StarDustCFW/StarDustCFWPack#6]
Hola de nuevo... como sabras ya creo yo, tinfoil no funciona en atmosphere 0.11.1...

Tenemos que usar ahora el cfw atmosphere Modificado para tinfoil el cual es este.
https://github.com/borntohonk/NEUTOS/releases/tag/0.11.1-NEUTOS

Favor de actualizar tu stardust con ese atmosphere modificado para tinfoil.. gracias de nuevo por tus aportes :)

**Comment by PASTO666** [comment]
No es nesesario cambiar a ese cfw modificado, cambias solo el folder de (sep) el cual trae aquel pack modificado el cual hace la magia que funcione tinfoil en el atmosphere normal jaja xD

**Comment by PASTO666** [comment]
Stardust has to be updated with this custom atmosphere 0.11.1 modded so we can be able to use Tinfoil shop again with stardust.. thx again for your https://github.com/borntohonk/NEUTOS/releases/tag/0.11.1-NEUTOS

**Comment by Kronos2308** [comment]
yes ams put a sigpatches verification for ver 10.0.0 and higer
so tinfoil and other games won't work 
for the moment i put a patch in the toolkit  
downlod Zenten Shop an also will apply  a tem patch for makeal  work
