### ISSUE TITLE
Please add the patch that allow us see the games portraits with Tinfoil with out an sx os license

### ISSUE THREAD

**Issue by PASTO666** [StarDustCFW/StarDustCFWPack#7]
as title says, The fellow that works NEUTOS, has released a new update with that!!! works perfect and all but i love StarDustCFW bettah... if u put that UFFF it will be bettah our tinfoil with STARDUST pack..

here its link so you can test your tinfoil with it and will see that it will allow you to change the games view to portraits with out an sx os license :)

https://github.com/borntohonk/NEUTOS/releases/download/0.12.0-NEUTOS/atmosphere-0.12.0-neutos-a325c611+hbl-2.3.1+hbmenu-3.3.0.zip

And a new update for nxthemeinstaller has been released for firmware 10.0.1, heres the link in case you havent updated it.

https://github.com/exelix11/SwitchThemeInjector/releases/download/v-4.4-1/NXThemesInstaller.nro

PD: atmosphere version 12 also as been released.

**Comment by Kronos2308** [comment]
@i cant see any path is recent or is old

**Comment by Kronos2308** [comment]
patch inserted enjoy @PASTO666

**Comment by PASTO666** [comment]
thank you!!!!!!! you are the best jaja xD loving much bettah STARDUST :)
